trigger:
- master
- new-feature-branch

pool:
  name: 'Default'
  demands:
  - agent.name -equals popo

variables:
  pathToProjectFile: '$(System.DefaultWorkingDirectory)/HelloWorldApp/HelloWorldApp.csproj'
  buildConfiguration: 'Release'
  sonarQubeProjectKey: 'HelloWorld'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git checkout new-feature-branch || git checkout -b new-feature-branch
    git push origin new-feature-branch
    echo "Build Source Branch: $BUILD_SOURCEBRANCH"
    echo "Expected Branch: refs/heads/new-feature-branch"
    echo "$(git rev-parse --abbrev-ref HEAD)"
  displayName: 'Create New Branch'


- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'MSBuild'
    projectKey: '$(sonarQubeProjectKey)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/new-feature-branch'))
  displayName: 'Prepare SonarQube Analysis'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/new-feature-branch'))
  displayName: 'Restore NuGet Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --verbosity detailed'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/new-feature-branch'))
  displayName: 'Build Project'

- task: SonarQubeAnalyze@6
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/new-feature-branch'))
  displayName: 'Run SonarQube Analysis'

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/new-feature-branch'))
  displayName: 'Publish Quality Gate Result'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPush: '$(System.DefaultWorkingDirectory)/HelloWorldApp/bin/$(buildConfiguration)/*.nupkg'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildId'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/new-feature-branch'))
  displayName: 'Create NuGet Package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/HelloWorldApp/bin/$(buildConfiguration)'
    ArtifactName: '$(Build.SourceBranchName)_$(Build.BuildId)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/new-feature-branch'))
  displayName: 'Publish Artifact'

- script: |
    echo "Artifact: $(Build.SourceBranchName)_$(Build.BuildId)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/new-feature-branch'))
  displayName: 'Print Artifact Name'


- task: SendEmail@1
  inputs:
    To: 'yohaycasoy@gmail.com'
    From: 'yohaycasoy@gmail.com'
    Subject: 'Build $(Build.BuildId) Status'
    Body: 'The build and analysis for branch $(Build.SourceBranchName) has completed with status $(Build.Status).'
    BodyAsHtml: false
    AddAttachment: false
    UseSSL: false