trigger:
- master

pool:
  name: 'Default'
  demands:
  - agent.name -equals popo

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --verbosity detailed'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --verbosity detailed'
    publishWebProjects: false

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(System.DefaultWorkingDirectory)/HelloWorldApp/*.nupkg'
    publishVstsFeed: 'HelloWorldApp'



- script: echo Build and publish completed successfully.
  displayName: 'Confirmation Message'
