trigger:
- master

pool:
  name: 'Default'
  demands:
  - agent.name -equals popo

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

